export const seeddata = [
  {
    cadreCode: "IAS",
    cadre: "Indian Administrative Services (IAS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "IPS",
    cadre: "Indian Police Service (IPS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Sikkim Police",
  },
  {
    cadreCode: "IFS",
    cadre: "Indian Forest Services (IFS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Forest Environment & Wildlife Department",
  },
  {
    cadreCode: "SCS",
    cadre: "State Civil Service (SCS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSPS",
    cadre: "Sikkim State Police service(SSPS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Sikkim Police",
  },
  {
    cadreCode: "SSFS",
    cadre: "Sikkim State Forest Service (SSFS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Forest Environment & Wildlife Department",
  },
  {
    cadreCode: "SSFS",
    cadre: "Sikkim State Finance Service(SSFS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Finance Department",
  },
  {
    cadreCode: "SSES",
    cadre: "Sikkim State Engineering Service (SSES)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: null,
  },
  {
    cadreCode: "SSEES",
    cadre: "Sikkim State Electrical Engineering Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: null,
  },
  {
    cadreCode: "AHVS",
    cadre: "Animal Husbandry & Vatnery (AH&VS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Animal Husbandry LF & VS Department",
  },
  {
    cadreCode: "SSDS",
    cadre: "Sikkim State Dental Services",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "PARA",
    cadre: "PARA MEDICAL",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "STATS",
    cadre: "STATS.",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Planning & Development Department",
  },
  {
    cadreCode: "ARCHT",
    cadre: "ARCHT",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Buildings & Housing Dept",
  },
  {
    cadreCode: "PRISON",
    cadre: "PRISON",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Home Department",
  },
  {
    cadreCode: "COOP",
    cadre: "COOPERATIVE",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Co-operation Department",
  },
  {
    cadreCode: "NURSE",
    cadre: "NURSING",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "DHH",
    cadre: "DHH",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Commerce & Industries Department",
  },
  {
    cadreCode: "UNORG",
    cadre: "UNORGANISED",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SYA",
    cadre: "SPORTS & YOUTH AFFAIRS",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Sports & Youth Affairs Department",
  },
  {
    cadreCode: "STG1",
    cadre: "STENO GRADE I",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "STG2",
    cadre: "STENO GRADE II",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "STSERV",
    cadre: "STENO SERV",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "MNG",
    cadre: "MINES AND GEO.",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Mines & Geo Department",
  },
  {
    cadreCode: "MV",
    cadre: "MOTOR VEHICLE",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Transport Department",
  },
  {
    cadreCode: "HHA",
    cadre: "HOUSE HOLD AFFAIRS",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Home Department",
  },
  {
    cadreCode: "SPEC",
    cadre: "SPEC",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "LEGAL",
    cadre: "LEGAL SERV",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Law & Legislatative Affairs Department",
  },
  {
    cadreCode: "PNS",
    cadre: "P&S",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment:
      "Department of Personnel & Printing & Stationeries",
  },
  {
    cadreCode: "AGENG",
    cadre: "AGRI ENG",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment:
      "Agriculature, Hoticultural & Cashcrop Department",
  },
  {
    cadreCode: "FIRE",
    cadre: "FIRE",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Police",
  },
  {
    cadreCode: "GDPH",
    cadre: "Gen Doctors & Physical Health",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "RDD",
    cadre: "RDD",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "RDD",
  },
  {
    cadreCode: "CRAFT",
    cadre: "CRAFTMANSHIP",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Commerce & Industries Department",
  },
  {
    cadreCode: "LABOR",
    cadre: "LABOR",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Labour Department",
  },
  {
    cadreCode: "SPCB",
    cadre: "STATE POLL. CTRL BRD",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Forest Environment & Wildlife Department",
  },
  {
    cadreCode: "REVS",
    cadre: "REVENUE SERVICE",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Finance Department",
  },
  {
    cadreCode: "IT",
    cadre: "Information Technology",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Information Technology Department",
  },
  {
    cadreCode: "SSSME",
    cadre: "Sikkim State Subordinate Ministrial & Executives",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSSPS",
    cadre: "Sikkim State Subordinate Police service(SSPS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Sikkim Police",
  },
  {
    cadreCode: "SSSFS",
    cadre: "Sikkim State Subordinate Forest Service (SSFS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Forest Environment & Wildlife Department",
  },
  {
    cadreCode: "SSSFS",
    cadre: "Sikkim State Subordinate Finance Service(SSFS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Finance Department",
  },
  {
    cadreCode: "SSSES",
    cadre: "Sikkim State Subordinate Engineering Service (SSES)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: null,
  },
  {
    cadreCode: "SSSEES",
    cadre: "Sikkim State Subordinate Electrical Engineering Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: null,
  },
  {
    cadreCode: "SSAHVS",
    cadre: "Sikkim State Subordinate Animal Husbandry & Vatnery (AH&VS)",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Animal Husbandry LF & VS Department",
  },
  {
    cadreCode: "SSSDS",
    cadre: "Sikkim State Subordinate Dental Services",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "SSPMS",
    cadre: "Sikkim State Subordinate Para Medical Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "SSSSS",
    cadre: "Sikkim State Subordinate Statistical service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Planning & Development Department",
  },
  {
    cadreCode: "SSSAS",
    cadre: "Sikkim State Subordinate Architechture Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Buildings & Housing Dept",
  },
  {
    cadreCode: "SSSPS",
    cadre: "Sikkim State Subordinate Prison Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Home Department",
  },
  {
    cadreCode: "SSSCS",
    cadre: "Sikkim State Subordinate Cooperation Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Co-operation Department",
  },
  {
    cadreCode: "SSNS",
    cadre: "Sikkim State Nursing Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "SSSHHS",
    cadre: "Sikkim State Subordinate Handicraft & Handloom Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Commerce & Industries Department",
  },
  {
    cadreCode: "SSSUS",
    cadre: "Sikkim State Subordinate Unorganised Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSSSYAS",
    cadre: "Sikkim State Subordinate Sports & Youth Affairs Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Sports & Youth Affairs Department",
  },
  {
    cadreCode: "SSSG1S",
    cadre: "Sikkim State Subordinate Steno Grade I Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSSG2S",
    cadre: "Sikkim State Subordinate Steno Grade II Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSSS",
    cadre: "Sikkim State Subordinate Steno Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Department of Personnel",
  },
  {
    cadreCode: "SSSMGS",
    cadre: "Sikkim State Subordinate Mines & Geo Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Mines & Geo Department",
  },
  {
    cadreCode: "SSSMVS",
    cadre: "Sikkim State Subordinate Moter Vehicle Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Transport Department",
  },
  {
    cadreCode: "SSSHAS",
    cadre: "Sikkim State Subordinate HOUSE HOLD AFFAIRS Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Home Department",
  },
  {
    cadreCode: "SSSSS",
    cadre: "Sikkim State Subordinate SPEC Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Health & FW Department",
  },
  {
    cadreCode: "SSSLS",
    cadre: "Sikkim State Subordinate Legal Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Law & Legislatative Affairs Department",
  },
  {
    cadreCode: "SSSPS",
    cadre: "Sikkim State Subordinate P&S",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment:
      "Department of Personnel & Printing & Stationeries",
  },
  {
    cadreCode: "SSAES",
    cadre: "Sikkim State Subordinate Agriculture Engineering Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment:
      "Agriculature, Hoticultural & Cashcrop Department",
  },
  {
    cadreCode: "SSSFS",
    cadre: "Sikkim State Subordinate Fire Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Police",
  },
  {
    cadreCode: "SSSRS",
    cadre: "Sikkim State Subordinate RDD Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "RDD",
  },
  {
    cadreCode: "SSSCS",
    cadre: "Sikkim State Subordinate Craftmanship Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Commerce & Industries Department",
  },
  {
    cadreCode: "SSSLS",
    cadre: "Sikkim State Subordinate Labour Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Labour Department",
  },
  {
    cadreCode: "SSSPCBS",
    cadre: "Sikkim State Subordinate State Pollution Control Board Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Forest Environment & Wildlife Department",
  },
  {
    cadreCode: "SSSRS",
    cadre: "Sikkim State Subordinate Revenue Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Finance Department",
  },
  {
    cadreCode: "SSSITS",
    cadre: "Sikkim State Subordinate Information Technology Service",
    cadreControllingAdministrativeAuthority: "Department of Personnel",
    cadreControllingDepartment: "Information Technology Department",
  },
];
